[package]
name = "flowscope-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.flowscope]
path = ".."
features = [
    "arp",
    "cdp",
    "dhcp",
    "dns",
    "extractors",
    "http",
    "icmp",
    "lldp",
    "ndp",
    "ntp",
    "reassembler",
    "session",
    "ssh",
    "tls",
    "tracker",
]

[[bin]]
name = "arp"
path = "fuzz_targets/arp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dns_udp"
path = "fuzz_targets/dns_udp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dns_tcp"
path = "fuzz_targets/dns_tcp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "http"
path = "fuzz_targets/http.rs"
test = false
doc = false
bench = false

[[bin]]
name = "icmp"
path = "fuzz_targets/icmp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "tls"
path = "fuzz_targets/tls.rs"
test = false
doc = false
bench = false

[[bin]]
name = "tls_handshake"
path = "fuzz_targets/tls_handshake.rs"
test = false
doc = false
bench = false

[[bin]]
name = "layers"
path = "fuzz_targets/layers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ndp"
path = "fuzz_targets/ndp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dhcp"
path = "fuzz_targets/dhcp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lldp"
path = "fuzz_targets/lldp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cdp"
path = "fuzz_targets/cdp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ntp"
path = "fuzz_targets/ntp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ssh"
path = "fuzz_targets/ssh.rs"
test = false
doc = false
bench = false
