name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format check
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --all-features --verbose
    - name: Clippy
      run: cargo clippy --all-features --all-targets -- -D warnings
    - name: Run tests
      run: cargo test --all-features --verbose
    - name: Doc build
      run: cargo doc --all-features --no-deps
      env:
        RUSTDOCFLAGS: -D warnings
